project_id = "zqxepggmlxyhzjgiwusb"

[functions.chat]
verify_jwt = false

[functions.gemini-live]
verify_jwt = false

[functions.gemini-tts]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false